### PR TITLE
New, modern documentation theme with built-in search

### PR DESCRIPTION
**Pull request by metasim**
Depends on #301

### CODE REVIEW

**Comment by metasim** [comment]
View CI build of docs here:

https://1292-174014757-gh.circle-artifacts.com/0/rf-site/index.html

**Comment by vpipkt** [comment]
Once all the #301 things are sorted this is great.

**Comment by vpipkt** [comment]
@metasim on your local web server do you get bad links when clicking the search result. In the Circle one i get links like 

https://1292-174014757-gh.circle-artifacts.com/0/rf-site//nodata-handling.html#nodata-and-local-arithmetic

And so the double slashes ahead of `nodata-handling` breaks the link.

**Comment by metasim** [comment]
> @metasim on your local web server do you get bad links when clicking the search result. In the Circle one i get links like
> 
> https://1292-174014757-gh.circle-artifacts.com/0/rf-site//nodata-handling.html#nodata-and-local-arithmetic
> 

If you change the double `//` to `/` it should work.

**Pull request merged**
