### PR TITLE
Generate Python Users Manual from scripts

### PR DESCRIPTION
**Pull request by metasim**
This PR implements the mechanics and provides scaffolding for a new, Python-centric user manual with evaluated code blocks. Suggesting we use subsequent PRs for the actual content.

Depends on #144

### CODE REVIEW

**Comment by vpipkt** [comment]
Another one to consider:

* https://github.com/pystitch/stitch

**Comment by metasim** [comment]
Also:

* https://github.com/jankatins/knitpy
* https://github.com/mwouts/jupytext

**Comment by metasim** [comment]
NB: We ideally need something that goes from `.pymd` to `.md`, in order to integrate with rest of documentation system.

**Comment by metasim** [comment]
Given that we've decided on the `.pymd` &rarr; `.md` pathway (for the time being), which is supported by multiple tool chains, I'm going to stick with pweave for the moment given that it's working in our current configuration, and can be replaced at a later date.

**Pull request merged**
