### PR TITLE
Fix for 68

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by vpipkt** [comment]
I'm looking at this now... more to come

**Comment by vpipkt** [comment]
Some inconsistencies seem to remain. 

Now if you observe the last Row of tiles in the output (those whose tiles are 221 rows tall), you will see some stretching of the features there, as if the tile was 256 cells tall.

**Comment by metasim** [comment]
@vpipkt Thanks for the juxtapose view.... I never would have picked up on that.

**Comment by metasim** [comment]
I'm going to merge this, but keep the bug open, so as to refine from here.

**Comment by vpipkt** [comment]
Looks like #68 got closed?

**Pull request merged**
