### PR TITLE
Geotrellis 3.x

### PR DESCRIPTION
**Pull request by metasim**
# Geotrellis 3.x Upgrade Log

* Add `Int` type parameter to `Grid`
* Add `Int` type parameter to `CellGrid`
* Add `Int` type parameter to `GridBounds`... or `TileBounds`
* Use `GridBounds.toGridType` to coerce from `Int` to `Long` type parameter
* Update imports for layers, particularly `geotrellis.spark.tiling` to `geotrellis.layer`
* Update imports for `geotrellis.spark.io` to `geotrellis.spark.store...`
* Removed `FixedRasterExtent`
* Removed `org.locationtech.rasterframes.util.Shims`
* Change `Extent.jtsGeom` to `Extent.toPolygon`
* Change `TileLayerMetadata.gridBounds` to `TileLayerMetadata.tileBounds`
* Add `geotrellis-gdal` dependency
* Remove any conversions between JTS geometry and old `geotrellis.vector` geometry
* Changed `org.locationtech.rasterframes.encoders.StandardEncoders.crsEncoder` to `crsSparkEncoder`
* Change `(cols, rows)` dimension destructuring to `Dimensions(cols, rows)`
* Revisit use of `Tile` equality since [it's more strict](https://github.com/locationtech/geotrellis/pull/2991)
* Update `reference.conf` to use `geotrellis.raster.gdal` namespace.
* Replace all uses of `TileDimensions` with `geotrellis.raster.Dimensions[Int]`.

## TODO

* [x] PR to GT to make `FixedDelegatingTile` obsolete. (cf https://github.com/locationtech/geotrellis/issues/3153)
* [x] Replace `TileDimension` with `geotrellis.raster.Dimensions`
* [ ] Local `RasterSource` updated to use `CellGrid[Long]` 
* [ ] Replace `SimpleRasterInfo` with `GeoTiffInfo` (where possible). Revisit `RasterExtent` vs `GridExtent[Long]`
* [ ] Replace all `Fixed*` classes.
* [ ] Remove `RasterSource` altogether.
* [ ] Replace `spray-json` with `circe`.

### CODE REVIEW

**Comment by metasim** [comment]
Depends on https://github.com/locationtech/geotrellis/issues/3134

**Comment by pomadchin** [comment]
@metasim you can depend on GeoTrellis 3.1.0 and use GeoTrellis projected like now.

**Comment by metasim** [comment]
@pomadchin Got pulled onto other work.... definitely near the top of my RF todo list.

**Comment by metasim** [comment]
@pomadchin GT 3.1.0 working great!

**Pull request merged**
