### PR TITLE
Another attempt at getting travis to use correct python version.

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by vpipkt** [comment]
How do you like them 🍎 

https://travis-ci.org/locationtech/rasterframes/builds/562598612#L4223-L4227

`ImportError No module named 'setuptools'`

**Comment by metasim** [comment]
This is ready to review and merge... the outstanding build errors are python test errors, which can be fixed in a separate PR.

**Comment by vpipkt** [comment]
The only other thing I see is https://travis-ci.org/locationtech/rasterframes/builds/565616856#L4687-L4715

**Comment by metasim** [comment]
> The only other thing I see is https://travis-ci.org/locationtech/rasterframes/builds/565616856#L4687-L4727

I think this is just a warning from gdal installation.

**Pull request merged**
